export const LOGIN_PATH = '/login'
export const SIGN_PATH = '/signup'
export const RESET_PASSWORD_PATH = '/reset-password'
export const HOME_PATH = '/'
export const LAST_CHECKED_USER_INFO = 'last_checked_user_info'
export const COOKIE_AUTH_INFO = 'authInfo'
export const USER_SESSION = 'user_session'
export const LOGIN_NAME = 'loginName'